In [1]:
import numpy as np

In [2]:
#create - from list 
arr = np.array([1,2,3,4,5])
print(arr,type(arr),arr.shape)

arr2 = np.array([1,2,3,4,5,"String"])
print(arr2,type(arr2) , arr2.dtype,arr.shape)

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D , arr2D.shape)


[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'String'] <class 'numpy.ndarray'> <U21 (5,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [3]:
# zeros Create 
arr1 = np.zeros((2,3) , dtype= "int64")
print(arr1, arr1.shape)

# ones Create 
arr2 = np.ones((2,3) , dtype= "int64")
print(arr2, arr2.shape)

# if we want to create a one dimensional array 
arr3 = np.ones((5,))
print(arr3)

# function called full
arr4 = np.full((3,4) , 100) #prefilled with 100
print(arr4 , arr4.shape)

#identity matrix
arr5 = np.eye(3) # identity value 
print(arr5, arr5.shape)

#Range function
arr6 = np.arange(1,11,2)
print(arr6)

arr7 = np.linspace(1 , 100 , 4) #evenly spaced arrays
print(arr7,arr7.shape)


[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[1. 1. 1. 1. 1.]
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[1 3 5 7 9]
[  1.  34.  67. 100.] (4,)


In [4]:
# PROPERTIES
arr10 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr10.shape) # prints the dimension of the array (m,n)
print(arr10.size)  # prints the total number of ekements 
print(arr10.dtype)  # prints the data type in array
print(arr10.ndim) # prints the dimention type 1D 2D 3D 

#if we already have an existing array and we want to type cast that means change its type
float_array = arr.astype(np.float64)
print(float_array , float_array.dtype)

(3, 3)
9
int64
2
[1. 2. 3. 4. 5.] float64


In [5]:
# opperations on array

arr = np.array([[1,2,3],[4,5,6]])
print(arr ,arr.shape )

#reshaping the arr
reshaped = arr.reshape((3,2))
print(reshaped ,reshaped.shape )

flattened = arr.flatten() # converts 2d into 2d
print(flattened , flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [6]:
# indexing 

#on a plain 1 d array
arr = np.array([1,2,3,4,5])

print(arr[0])  # output - 1
print(arr[3])  # output - 4

print("\n")
# on a 2D array
arr12 = np.array([[1,2,3],[4,5,6]])
print(arr12[0][0])
print(arr12[0][1])
print(arr12[0][2])
print(arr12[1][0])
print(arr12[1][1])
print(arr12[1][2])


1
4


1
2
3
4
5
6


In [7]:
# Fancy Indexing

arr = np.array([1,2,3,4,5])

idx = [0,1,3]
print(arr[idx])

[1 2 4]


In [8]:
# Boolean Indexing
arr = np.array([1,2,3,4,5])

print(arr[arr > 3])
print(arr[arr % 2 != 0])

[4 5]
[1 3 5]


In [9]:
# Slicing

arr = np.array([1 ,2 ,3 ,4 ,5])

print(arr[1:4]) # [start , end , step]
print(arr[1: ]) # [start , end , step]
print(arr[ :4]) # [start , end , step]
print(arr[ :4:3]) # [start , end , step]
print(arr[ ::2]) # [start , end , step]

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 4]
[1 3 5]


In [10]:
# DATA TYPES

arr = np.array([1,2,3.144,5])

print(arr , arr.dtype)


#complexnumbers
arr2 = np.array([3+5j])
print(arr2,arr2.dtype)

#objects
arr3 = np.array([{1,2,3},"abcd",3.14])
print(arr3 , arr3.dtype)

[1.    2.    3.144 5.   ] float64
[3.+5.j] complex128
[{1, 2, 3} 'abcd' 3.14] object


In [11]:
# Multi Dimensional Array

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_columns = np.sum(arr2D , axis = 0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D , axis = 1)
print(sum_of_rows)

#we can do slicig axis wise as well
print(arr2D[0:2 , 1:2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [12]:
# 3D array

arr3D = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]]) # 2x3x2
print(arr3D,arr3D.shape)

#indexing
print(arr3D[0,1,1])

#Slicing
print(arr3D[ :, 0 ,: ]) # this will get us first row from both layers
print(arr3D[ :,  : ,0]) # this will get us first column from both layers

# we can manupulate data using this

arr3D[:,0,:] = 99
print(arr3D)



[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [13]:
# Vecorization

arr = np.array([1,2,3,4,5,6])
print(arr ** 2)

[ 1  4  9 16 25 36]


In [14]:

# Broadcasting

arr = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5] , [1,2,3,4,5]])

print(arr+arr2)

[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [17]:
# Normalise

arr = np.array([[1,2],[3,4]])

mean = (np.mean(arr))  #mean 
std_dev= (np.std(arr))   # standard deviation

normalized_arr = (arr-mean)/std_dev
print(normalized_arr)


[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [23]:
# mathematical fnx

#aggregation
arr = np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.prod(arr))  #product of all
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))  # returns the address of min value
print(np.argmax(arr))  #returns the address of max value

print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
 print(np.var(arr))

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [25]:
# Power functions
arr = np.array([1,2,3,4,5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))


[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [30]:
#Log related to function
arr = np.array([1,2,3,4,5])
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [38]:
# Round of
print(np.round(3.14))
print(np.ceil(3.14)) #used for rounding up
print(np.floor(3.14)) #used for rounding up
print(np.trunc(3.14))

arr = np.array([1,2,3,4,5])
print(np.unique(arr)) #shows all unique values
print(np.sort(arr)) #do the sorting values
print(np.abs(arr)) # create absolute value without positive or negativbe sign


3.0
4.0
3.0
3.0
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
